import React, { useRef, useState } from "react";
import ReactMarkdown from "react-markdown";
import "./App.css";

function App() {
  const fileInputRef = useRef(null);
  const documentsRef = useRef(null);
  const questionsRef = useRef(null);

  const [message, setMessage] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [pdfUrl, setPdfUrl] = useState(null);

  const [uploading, setUploading] = useState(false);
  const [uploadMessage, setUploadMessage] = useState("");

  const [messages, setMessages] = useState([]);
  const [asking, setAsking] = useState(false);

  // Dynamic questions generated by Llama
  const [suggestedQuestions, setSuggestedQuestions] = useState([]);


  // =========================================================
  // CHOOSE PDF
  // =========================================================

  const handleChooseFile = () => {
    fileInputRef.current?.click();
  };


  // =========================================================
  // MY DOCUMENTS
  // =========================================================

  const handleMyDocuments = () => {
    documentsRef.current?.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });
  };


  // =========================================================
  // SAMPLE QUESTIONS
  // =========================================================

  const handleSampleQuestions = () => {
    questionsRef.current?.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });
  };


  // =========================================================
  // PDF UPLOAD
  // =========================================================

  const handleFileChange = async (event) => {

    const file = event.target.files?.[0];

    if (!file) {
      return;
    }


    // Check PDF
    if (
      file.type !== "application/pdf" &&
      !file.name.toLowerCase().endsWith(".pdf")
    ) {
      setUploadMessage("Please select a PDF file.");

      event.target.value = "";

      return;
    }


    // Revoke previous PDF URL
    if (pdfUrl) {
      URL.revokeObjectURL(pdfUrl);
    }


    // Set selected PDF
    setSelectedFile(file);


    // Create PDF preview
    const fileUrl = URL.createObjectURL(file);

    setPdfUrl(fileUrl);


    // Clear previous chat
    setMessages([]);


    // Clear previous questions
    setSuggestedQuestions([]);


    // Clear input
    setMessage("");


    // Start upload
    setUploading(true);

    setUploadMessage(
      "Uploading and indexing PDF..."
    );


    const formData = new FormData();

    formData.append("file", file);


    try {

      const response = await fetch(
        "http://127.0.0.1:8000/upload-pdf",
        {
          method: "POST",
          body: formData
        }
      );


      const data = await response.json();


      console.log(
        "Upload response:",
        data
      );


      if (!response.ok) {

        throw new Error(
          data.detail || "Upload failed"
        );

      }


      setUploadMessage(
        `PDF uploaded successfully — ${data.total_chunks} chunks indexed`
      );


    } catch (error) {

      console.error(
        "Upload error:",
        error
      );


      setUploadMessage(
        "Failed to upload PDF. Make sure FastAPI is running."
      );


    } finally {

      setUploading(false);

    }

  };


  // =========================================================
  // ASK QUESTION
  // =========================================================

  const askQuestion = async (question) => {

    const cleanQuestion =
      question?.trim();


    // Validation
    if (
      !cleanQuestion ||
      asking ||
      !selectedFile
    ) {
      return;
    }


    // Add user message
    const userMessage = {
      role: "user",
      content: cleanQuestion
    };


    setMessages(
      (previousMessages) => [
        ...previousMessages,
        userMessage
      ]
    );


    // Clear input
    setMessage("");


    // Clear old suggested questions
    // They will be replaced after the new answer
    setSuggestedQuestions([]);


    // Start loading
    setAsking(true);


    try {

      const response = await fetch(
        `http://127.0.0.1:8000/ask?query=${encodeURIComponent(
          cleanQuestion
        )}`
      );


      const data = await response.json();

console.log("================================");
console.log("FULL BACKEND RESPONSE:");
console.log(data);
console.log("================================");

console.log(
  "Suggested questions received:",
  data.suggested_questions
);

if (!response.ok) {
  throw new Error(
    data.detail || "Failed to get answer"
  );
}


// Add AI response
const assistantMessage = {
  role: "assistant",
  content:
    data.answer ||
    "I could not generate an answer.",
  sources: data.sources || []
};

setMessages(
  (previousMessages) => [
    ...previousMessages,
    assistantMessage
  ]
);


// Update suggested questions
if (
  Array.isArray(
    data.suggested_questions
  )
) {

  console.log(
    "Setting suggested questions:",
    data.suggested_questions
  );

  setSuggestedQuestions(
    data.suggested_questions
  );

} else {

  console.log(
    "No suggested_questions array received"
  );

  setSuggestedQuestions([]);

}


    } catch (error) {

      console.error(
        "Ask question error:",
        error
      );


      const errorMessage = {
        role: "assistant",

        content:
          "Sorry, I couldn't get an answer. Please make sure the FastAPI backend is running and a PDF has been indexed.",

        sources: []
      };


      setMessages(
        (previousMessages) => [
          ...previousMessages,
          errorMessage
        ]
      );


      setSuggestedQuestions([]);


    } finally {

      setAsking(false);

    }

  };


  // =========================================================
  // SEND MESSAGE
  // =========================================================

  const handleSend = () => {

    askQuestion(message);

  };


  // =========================================================
  // COPY ANSWER
  // =========================================================

  const copyAnswer = async (answer) => {

    try {

      await navigator.clipboard.writeText(
        answer
      );

      alert("Answer copied!");

    } catch (error) {

      console.error(
        "Copy failed:",
        error
      );

    }

  };


  // =========================================================
  // CLICK SUGGESTED QUESTION
  // =========================================================

  const handleQuestion = (question) => {

    if (
      !question ||
      asking ||
      !selectedFile
    ) {
      return;
    }


    console.log(
      "Suggested question clicked:",
      question
    );


    // Put question into input
    setMessage(question);


    // Directly ask the question
    askQuestion(question);

  };


  // =========================================================
  // REMOVE PDF
  // =========================================================

  const handleRemoveFile = () => {

    if (pdfUrl) {

      URL.revokeObjectURL(
        pdfUrl
      );

    }


    setSelectedFile(null);

    setPdfUrl(null);

    setUploadMessage("");

    setMessages([]);

    setSuggestedQuestions([]);

    setMessage("");


    // Reset file input
    if (fileInputRef.current) {

      fileInputRef.current.value = "";

    }

  };


  // =========================================================
  // RENDER
  // =========================================================

  return (

    <div className="app">


      {/* =====================================================
          SIDEBAR
      ===================================================== */}

      <aside className="sidebar">


        {/* LOGO */}

        <div className="logo-section">

          <div className="logo-icon">
            📄
          </div>

          <div>

            <h2>
              DocRAG
            </h2>

            <span>
              AI Document Assistant
            </span>

          </div>

        </div>


        {/* NAVIGATION */}

        <nav className="navigation">


          {/* CHAT */}

          <button
            className="nav-item active"
            onClick={() =>
              window.scrollTo({
                top: 0,
                behavior: "smooth"
              })
            }
          >

            <span>
              💬
            </span>

            <span>
              Chat
            </span>

          </button>


          {/* UPLOAD */}

          <button
            className="nav-item"
            onClick={handleChooseFile}
          >

            <span>
              📤
            </span>

            <span>
              Upload PDF
            </span>

          </button>


          {/* MY DOCUMENTS */}

          <button
            className="nav-item"
            onClick={handleMyDocuments}
          >

            <span>
              📁
            </span>

            <span>
              My Documents
            </span>

          </button>


          {/* SAMPLE QUESTIONS */}

          <button
            className="nav-item"
            onClick={handleSampleQuestions}
          >

            <span>
              ⭐
            </span>

            <span>
              Sample Questions
            </span>

          </button>


          {/* SETTINGS */}

          <button
            className="nav-item"
          >

            <span>
              ⚙️
            </span>

            <span>
              Settings
            </span>

          </button>


        </nav>


        {/* AI STATUS */}

        <div className="ai-status">

          <div className="status-title">

            <span className="status-dot"></span>

            AI Ready

          </div>


          <p>
            Powered by Llama 3.2 + RAG
          </p>


          <div className="progress">

            <div className="progress-bar"></div>

          </div>


          <small>

            {selectedFile
              ? "Document indexed"
              : "No document uploaded"}

          </small>

        </div>


      </aside>


      {/* =====================================================
          MAIN CONTENT
      ===================================================== */}

      <main className="main-content">


        {/* HEADER */}

        <header className="header">

          <div>

            <h1>

              Chat with Your{" "}

              <span>
                Documents
              </span>

            </h1>


            <p>
              Ask questions and get answers from your PDF
            </p>

          </div>


          <div className="profile">

            <button
              className="theme-button"
            >
              ☀️
            </button>


            <div className="avatar">
              S
            </div>


            <span>
              Sunil Kumar
            </span>


            <span>
              ▼
            </span>

          </div>

        </header>


        {/* =====================================================
            FEATURE CARDS
        ===================================================== */}

        {!selectedFile &&
          messages.length === 0 && (

            <section className="features">


              <div className="feature-card">

                <div className="feature-icon blue">
                  📄
                </div>

                <h3>
                  Upload PDF
                </h3>

                <p>
                  Add your document in seconds
                </p>

              </div>


              <div className="feature-card">

                <div className="feature-icon purple">
                  💬
                </div>

                <h3>
                  Ask Questions
                </h3>

                <p>
                  Get accurate answers from your content
                </p>

              </div>


              <div className="feature-card">

                <div className="feature-icon orange">
                  ⚡
                </div>

                <h3>
                  Find Insights
                </h3>

                <p>
                  Powered by RAG and Llama 3.2
                </p>

              </div>


            </section>

          )}


        {/* =====================================================
            UPLOAD SECTION
        ===================================================== */}

        <section className="upload-section">


          <div className="upload-icon">
            ☁️
          </div>


          <h3>
            Drag & drop a PDF here or click to browse
          </h3>


          <p>
            Supports PDF files only
          </p>


          <button
            className="choose-button"
            onClick={handleChooseFile}
            disabled={uploading}
          >

            {uploading
              ? "Uploading..."
              : "📤 Choose PDF"}

          </button>


          <input
            ref={fileInputRef}
            type="file"
            accept=".pdf,application/pdf"
            onChange={handleFileChange}
            style={{
              display: "none"
            }}
          />


          {/* UPLOAD MESSAGE */}

          {uploadMessage && (

            <p
              style={{
                marginTop: "15px",

                color: uploading
                  ? "#2563eb"
                  : uploadMessage.includes(
                      "successfully"
                    )
                  ? "#16a34a"
                  : "#dc2626",

                fontWeight: "600"
              }}
            >

              {uploadMessage}

            </p>

          )}


        </section>


        {/* =====================================================
            DOCUMENT CARD
        ===================================================== */}

        {selectedFile && (

          <section
            ref={documentsRef}
            className="document-card"
          >


            <div className="pdf-icon">
              PDF
            </div>


            <div className="document-info">

              <h3>
                {selectedFile.name}
              </h3>


              <p>

                {uploading
                  ? "Processing..."
                  : "Uploaded and indexed successfully"}

              </p>

            </div>


            <div className="success">
              ✓
            </div>


            <button
              className="remove-button"
              onClick={handleRemoveFile}
            >
              ×
            </button>


          </section>

        )}


        {/* =====================================================
            PDF PREVIEW
        ===================================================== */}

        {pdfUrl && (

          <section className="pdf-preview-section">


            <div className="pdf-preview-header">

              <div>

                <h3>
                  📄 Document Preview
                </h3>

                <p>
                  View your uploaded PDF
                </p>

              </div>


              <a
                href={pdfUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="open-pdf-button"
              >
                Open PDF ↗
              </a>


            </div>


            <div className="pdf-viewer">

              <iframe
                src={pdfUrl}
                title="PDF Preview"
              />

            </div>


          </section>

        )}


        {/* =====================================================
            CHAT MESSAGES
        ===================================================== */}

        {messages.length > 0 && (

          <section
            style={{
              marginTop: "25px",
              display: "flex",
              flexDirection: "column",
              gap: "15px",
              maxHeight: "450px",
              overflowY: "auto",
              padding: "5px"
            }}
          >


            {messages.map(
              (item, index) => (

                <div
                  key={index}
                  style={{
                    display: "flex",

                    justifyContent:
                      item.role === "user"
                        ? "flex-end"
                        : "flex-start"
                  }}
                >


                  <div
                    style={{
                      maxWidth: "75%",

                      background:
                        item.role === "user"
                          ? "#2563eb"
                          : "#ffffff",

                      color:
                        item.role === "user"
                          ? "#ffffff"
                          : "#1e293b",

                      border:
                        item.role === "assistant"
                          ? "1px solid #e2e8f0"
                          : "none",

                      borderRadius: "14px",

                      padding:
                        "14px 17px",

                      boxShadow:
                        "0 3px 10px rgba(15,23,42,0.05)"
                    }}
                  >


                    {/* MESSAGE HEADER */}

                    <div
                      style={{
                        fontSize: "12px",
                        fontWeight: "700",
                        marginBottom: "6px",
                        opacity: 0.7
                      }}
                    >

                      {item.role === "user"
                        ? "You"
                        : "🤖 DocRAG"}

                    </div>


                    {/* MESSAGE CONTENT */}

                    <div className="ai-answer">

                      <ReactMarkdown>

                        {item.content}

                      </ReactMarkdown>

                    </div>


                    {/* COPY BUTTON */}

                    {item.role === "assistant" && (

                      <button
                        className="copy-button"
                        onClick={() =>
                          copyAnswer(
                            item.content
                          )
                        }
                      >
                        📋 Copy
                      </button>

                    )}


                    {/* =================================================
                        SOURCES
                    ================================================= */}

                    {item.sources &&
                      item.sources.length > 0 && (

                        <div className="sources-container">


                          <div className="sources-title">
                            📚 Sources
                          </div>


                          {item.sources.map(
                            (
                              source,
                              sourceIndex
                            ) => (

                              <div
                                key={sourceIndex}
                                className="source-card"
                              >


                                <div className="source-header">

                                  <span className="source-number">

                                    {sourceIndex + 1}

                                  </span>


                                  <span className="source-label">

                                    Document Source

                                  </span>

                                </div>


                                <div className="source-text">

                                  {source.substring(
                                    0,
                                    220
                                  )}

                                  {source.length > 220
                                    ? "..."
                                    : ""}

                                </div>


                              </div>

                            )
                          )}


                        </div>

                      )}


                  </div>


                </div>

              )
            )}


            {/* =================================================
                LOADING
            ================================================= */}

            {asking && (

              <div
                style={{
                  alignSelf: "flex-start",

                  background: "#ffffff",

                  border:
                    "1px solid #e2e8f0",

                  borderRadius: "14px",

                  padding: "14px 17px",

                  color: "#64748b",

                  fontSize: "13px"
                }}
              >

                🤖 Thinking...

              </div>

            )}


          </section>

        )}


        {/* =====================================================
            DYNAMIC SUGGESTED QUESTIONS
        ===================================================== */}

        {selectedFile && messages.length > 0 && (

<section
  ref={questionsRef}
  className="questions-section"
>

  <h3>
    Try asking something:
  </h3>

  {suggestedQuestions.length > 0 ? (

    <div className="questions">

      {suggestedQuestions.map(
        (question, index) => (

          <button
            key={`${question}-${index}`}
            type="button"
            className="question-button"
            onClick={() =>
              handleQuestion(question)
            }
            disabled={asking}
          >
            {question}
          </button>

        )
      )}

    </div>

  ) : (

    <p
      style={{
        color: "#64748b",
        fontSize: "12px"
      }}
    >
      No suggested questions received.
    </p>

  )}

</section>
          )}


        {/* =====================================================
            BEFORE PDF UPLOAD
        ===================================================== */}

        {!selectedFile && (

          <section className="questions-section">


            <h3>
              📄 Upload a PDF to get started
            </h3>


            <p
              style={{
                color: "#64748b",
                fontSize: "13px",
                marginTop: "6px"
              }}
            >

              Suggested questions will appear
              after you upload a document.

            </p>


          </section>

        )}


        {/* =====================================================
            CHAT INPUT
        ===================================================== */}

        <div className="chat-input-container">


          <button
            className="attachment-button"
            onClick={handleChooseFile}
            title="Upload PDF"
          >
            📎
          </button>


          <input
            type="text"

            placeholder={
              selectedFile
                ? "Ask something about your document..."
                : "Upload a PDF first..."
            }

            value={message}

            onChange={(event) =>
              setMessage(
                event.target.value
              )
            }

            onKeyDown={(event) => {

              if (
                event.key === "Enter" &&
                !event.shiftKey
              ) {

                event.preventDefault();

                handleSend();

              }

            }}

            disabled={
              asking ||
              !selectedFile
            }

          />


          <button
            className="send-button"

            onClick={handleSend}

            disabled={
              asking ||
              !selectedFile ||
              !message.trim()
            }
          >

            {asking
              ? "..."
              : "➤"}

          </button>


        </div>


      </main>


    </div>

  );
}

export default App;